title: "Cròniques de la Família"
description: "Una web per publicar les cròniques per períodes (patriarques) i les històries associades."
url: "" # opcional: https://usuari.github.io
baseurl: "" # opcional: /repositori
lang: ca
timezone: Europe/Madrid

theme: minima

# Col·leccions
collections:
  periodes:
    output: true
    permalink: /periodes/:name/
  histories:
    output: true
    permalink: /histories/:name/

defaults:
  - scope:
      path: ""
      type: "periodes"
    values:
      layout: periode
  - scope:
      path: ""
      type: "histories"
    values:
      layout: historia

# Plugins compatibles amb GitHub Pages
plugins:
  - jekyll-feed

markdown: kramdown
